persons/urls.py
from django.urls import path
from rest_framework import routers

from . import views
from .views import HomeView, ListClientView, ListWaiterView, RegisterClientView, RegisterWaiterView, UpdateClientView, \
    UpdateWaiterView, ClientDeleteView, WaiterDeleteView

app_name = 'persons'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('persons/clients_list', ListClientView.as_view(), name='client_list'),
    path('persons/add_client', RegisterClientView.as_view(), name='add_client'),
    path('persons/update_client/<int:pk>/', (UpdateClientView.as_view()), name='update_client'),
    path('persons/delete_client/<int:pk>/', (ClientDeleteView.as_view()), name='delete_client'),
    path('persons/waiter_list', ListWaiterView.as_view(), name='waiter_list'),
    path('persons/add_waiter', RegisterWaiterView.as_view(), name='add_Waiter'),
    path('persons/update_waiter/<int:pk>/', (UpdateWaiterView.as_view()), name='update_waiter'),
    path('persons/delete_waiter/<int:pk>/', (WaiterDeleteView.as_view()), name='delete_waiter'),
    # path('register_user', RegisterView.as_view(), name='register_user'),
    # path('login/', LoginView.as_view(), name='login'),
    # path('logout/', LogoutView.as_view(), name='logout'),
    ]

router = routers.DefaultRouter()
router.register(r'client', views.ClientViewSet)
router.register(r'waiter', views.WaiterViewSet)

restaurant/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework_simplejwt import views as jwt_views
from persons.urls import router as router_persons
from products.urls import router as router_products
from tables.urls import router as router_tables
from invoice.urls import router as router_invoices

urlpatterns = [
    path('api/order_products/', include(router_products.urls)),
    path('api/persons/', include(router_persons.urls)),
    path('api/tables/', include(router_tables.urls)),
    path('api/invoices/', include(router_invoices.urls)),
    path('', include('persons.urls')),
    path('invoices/', include('invoice.urls')),
    path('tables/', include('tables.urls')),
    path('products/', include('products.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('admin/', admin.site.urls),
    path('api/token/', jwt_views.TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', jwt_views.TokenRefreshView.as_view(), name='token_refresh'),
]

tables/urls.py
from django.urls import path
from rest_framework import routers

from . import views
from .views import ListTableView, RegisterTableView, UpdateTableView, DeleteTableView

app_name = 'table'

urlpatterns = [
    path('table_list', ListTableView.as_view(), name='table_list'),
    path('add_table', RegisterTableView.as_view(), name='add_Table'),
    path('update_table/<int:pk>/', UpdateTableView.as_view(), name='update_table'),
    path('delete_table/<int:pk>/', (DeleteTableView.as_view()), name='delete_table'),
    ]

router = routers.DefaultRouter()
router.register(r'tables', views.TableViewSet)

persons/models.py
from django.db import models

from django.db.models.signals import post_save
from django.dispatch import receiver


class Client(models.Model):
    name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    observations = models.CharField(max_length=50)

    def __str__(self):
        return f'{self.name} {self.last_name}'


class Waiter(models.Model):
    name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    last_name_2 = models.CharField(max_length=50)

    def __str__(self):
        return f'{self.name} {self.last_name}'

persons/forms.py
from django import forms
from django.forms import TextInput

from persons.models import Client, Waiter


class ClientForm(forms.ModelForm):
    class Meta:
        model = Client
        fields = ['name', 'last_name', 'observations']

        widgets = {
            'reference': TextInput(attrs={
                'class': "form-control mb-3",
                'style': 'max-width: 500px;',
            }),
        }


class WaiterForm(forms.ModelForm):
    class Meta:
        model = Waiter
        fields = ['name', 'last_name', 'last_name_2']
        widgets = {
            'reference': TextInput(attrs={
                'class': "form-control mb-3",
                'style': 'max-width: 500px;',
            }),
        }

persons/views.py
# from django.contrib.auth import logout, authenticate, login
# from django.contrib.auth.models import User
from django.urls import reverse_lazy
from django.views.generic import ListView, TemplateView, CreateView, UpdateView, DeleteView, FormView, RedirectView
# from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from rest_framework import viewsets, permissions

from persons.forms import ClientForm, WaiterForm
from persons.models import Client, Waiter
from persons.serializer import ClientSerializer, WaiterSerializer


class ClientViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows users to be viewed or edited.
    """
    queryset = Client.objects.all()
    serializer_class = ClientSerializer
    permission_classes = [permissions.IsAdminUser]


class WaiterViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows users to be viewed or edited.
    """
    queryset = Waiter.objects.all()
    serializer_class = WaiterSerializer
    permission_classes = [permissions.IsAdminUser]


class HomeView(TemplateView):
    """
        This view shows the home page of the app.
    """
    template_name = "base.html"


class ListClientView(ListView):
    model = Client
    queryset = Client.objects.all()
    template_name = 'persons/client_list.html'
    context_object_name = 'client_list'


class ListWaiterView(ListView):
    model = Waiter
    queryset = Waiter.objects.all()
    template_name = 'persons/waiter_list.html'
    context_object_name = 'waiter_list'


class RegisterClientView(CreateView):
    form_class = ClientForm
    model = Client
    template_name = 'persons/add_client.html'
    success_url = reverse_lazy('persons:client_list')


class RegisterWaiterView(CreateView):
    form_class = WaiterForm
    model = Waiter
    template_name = 'persons/add_waiter.html'
    success_url = reverse_lazy('persons:waiter_list')


class UpdateClientView(UpdateView):
    model = Client
    form_class = ClientForm
    pk_url_kwarg = 'pk'
    template_name = 'persons/add_client.html'
    success_url = reverse_lazy('persons:client_list')


class UpdateWaiterView(UpdateView):
    model = Waiter
    form_class = WaiterForm
    pk_url_kwarg = 'pk'
    template_name = 'persons/add_waiter.html'
    success_url = reverse_lazy('persons:waiter_list')


class ClientDeleteView(DeleteView):
    model = Client
    pk_url_kwarg = 'pk'
    template_name = 'persons/delete_client.html'
    success_url = reverse_lazy('persons:client_list')


class WaiterDeleteView(DeleteView):
    model = Waiter
    pk_url_kwarg = 'pk'
    template_name = 'persons/delete_waiter.html'
    success_url = reverse_lazy('persons:waiter_list')


# class LoginView(FormView):
#     form_class = AuthenticationForm
#     template_name = 'registration/login.html'
#     success_url = reverse_lazy('persons:home')
#
#     def form_valid(self, form):
#         username = form.cleaned_data['username']
#         password = form.cleaned_data['password']
#         user = authenticate(username=username, password=password)
#
#         if user is not None and user.is_active:
#             login(self.request, user)
#             return super(LoginView, self).form_valid(form)
#         else:
#             return self.form_invalid(form)
#
#
# class RegisterView(CreateView):
#     form_class = UserCreationForm
#     model = User
#     template_name = 'registration/register.html'
#     success_url = reverse_lazy('persons:home')
#
#
# class LogoutView(RedirectView):
#     url = reverse_lazy('persons:login')
#
#     def get(self, request, *args, **kwargs):
#         logout(request)
#         return super(LogoutView, self).get(request, *args, **kwargs)

templates/persons/add_client.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block tittle%} Add Client {%endblock%}

{% block content %}
<br>
<br>
<br>
<div class="container">
    <div class="row">
        <div class="col-12 col-md-6 offset-md-3">
            <div class="card" id="content-register">
                <div class="card-body">
                    <h3 class="text-center " style="color:dimgrey "> Add a Client</h3>
                    <hr>
                    <form method="POST">

                            {% csrf_token %}
                            {{ form | crispy }}
                             <input type="submit" name="submit" class="btn btn-success btn-md" value="Add">
                            <a class="btn btn-dark" href="{% url 'persons:client_list' %}"> Cancel </a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

templates/persons/add_waiter.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block tittle%} Add Waiter {%endblock%}

{% block content %}
<br>
<br>
<br>
<div class="container">
    <div class="row">
        <div class="col-12 col-md-6 offset-md-3">
            <div class="card" id="content-register">
                <div class="card-body">
                    <h3 class="text-center " style="color:dimgrey "> Add a Waiter</h3>
                    <hr>
                    <form method="POST">

                            {% csrf_token %}
                            {{ form | crispy }}
                             <input type="submit" name="submit" class="btn btn-success btn-md" value="Add">
                            <a class="btn btn-dark" href="{% url 'persons:waiter_list' %}"> Cancel </a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

templates/persons/client_list.html
{% extends 'base.html' %}

{% block tittle%} Pet list {%endblock%}

{% block content %}
<br>
<br>
<br>
<div class="container">
    <h3 class="text-center " style="color:#181818 ">Client List</h3>
    <table class="table" id="tabla" style="border: 1px solid darkgrey;
                        border-radius: 20px; background-color:#20c997; opacity:0.9; color:#181818">
        <thead>
            <tr>
                <th scope="col">ID</th>
                <th scope="col">Name</th>
                <th scope="col">Age</th>
                <th scope="col">Units</th>
            </tr>
        </thead>
        <tbody>
            {% for client in client_list %}
            <tr>

                <th scope="row">{{client.id}}</th>
                <td>{{client.name}}</td>
                <td>{{client.last_name}}</td>
                <td>{{client.observations}}</td>
                <td>
                    <a class="btn btn-primary" style="margin-right: 5px ;" href="{% url 'persons:update_client' client.pk %}">Edit</a>
                    <a class="btn btn-danger" href="{% url 'persons:delete_client' client.pk %}">Delete</a>
                </td>
        
            </tr>
            {% endfor %}
        </tbody>
        </table>

</div>

{% endblock content %}

templates/persons/delete_client.html
{% extends 'base.html' %}

{% block Title %} Delete Client{% endblock %}

{% block content %}
    <div class="d-flex justify-content-center">
        <form method="post" novalidate>
            {% csrf_token %}
            <h3 class="mt-5"> ¿Esta seguro de que desea borrar este client?</h3>
            <div class="text-center mt-4">
                <input value="Confirm" type="submit" class="btn btn-success text-center"/>
            </div>
        </form>
    </div>
{% endblock %}

templates/persons/delete_waiter.html
{% extends 'base.html' %}

{% block Title %} Delete Waiter{% endblock %}

{% block content %}
    <div class="d-flex justify-content-center">
        <form method="post" novalidate>
            {% csrf_token %}
            <h3 class="mt-5"> ¿Esta seguro de que desea borrar este Waiter?</h3>
            <div class="text-center mt-4">
                <input value="Confirm" type="submit" class="btn btn-success text-center"/>
            </div>
        </form>
    </div>
{% endblock %}

templates/persons/waiter_list.html
{% extends 'base.html' %}

{% block tittle%} Pet list {%endblock%}

{% block content %}
<br>
<br>
<br>
<div class="container">
    <h3 class="text-center " style="color:#181818 ">Waiter List</h3>
    <table class="table" id="tabla" style="border: 1px solid darkgrey;
                        border-radius: 20px; background-color:#20c997; opacity:0.9; color:#181818">
        <thead>
            <tr>
                <th scope="col">ID</th>
                <th scope="col">Name</th>
                <th scope="col">Last Name 1</th>
                <th scope="col">Last Name 2</th>
            </tr>
        </thead>
        <tbody>

            {% for waiter in waiter_list %}
            <tr>

                <th scope="row">{{waiter.id}}</th>
                <td>{{waiter.name}}</td>
                <td>{{waiter.last_name}}</td>
                <td>{{waiter.last_name_2}}</td>
                <td>
                    <a class="btn btn-primary" style="margin-right: 5px ;" href="{% url 'persons:update_waiter' waiter.pk %}">Edit</a>
                    <a class="btn btn-danger" href="{% url 'persons:delete_waiter' waiter.pk %}">Delete</a>
                </td>

            </tr>
            {% endfor %}

        </tbody>
        </table>

</div>

{% endblock content %}