products/urls.py
from django.urls import path
from rest_framework import routers

from . import views
from .views import ListTypeProductView, RegisterTypeProductView, UpdateTypeProductView, \
    DeleteTypeProductView, ListProductView, UpdateProductView, DeleteProductView, RegisterProductView, ListOrderView, \
    UpdateOrderView, RegisterOrderView, DeleteOrderView

app_name = 'products'

urlpatterns = [
    path('typeProduct_list', ListTypeProductView.as_view(), name='typeProduct_list'),
    path('add_typeProduct', RegisterTypeProductView.as_view(), name='add_typeProduct'),
    path('update_typeProduct/<int:pk>/', UpdateTypeProductView.as_view(), name='update_typeProduct'),
    path('delete_typeProduct/<int:pk>/', DeleteTypeProductView.as_view(), name='delete_typeProduct'),

    path('product_list', ListProductView.as_view(), name='product_list'),
    path('add_product', RegisterProductView.as_view(), name='add_product'),
    path('update_product/<int:pk>/', UpdateProductView.as_view(), name='update_product'),
    path('delete_product/<int:pk>/', DeleteProductView.as_view(), name='delete_product'),

    path('order_list', ListOrderView.as_view(), name='order_list'),
    path('add_order', RegisterOrderView.as_view(), name='add_order'),
    path('update_order/<int:pk>/', UpdateOrderView.as_view(), name='update_order'),
    path('delete_order/<int:pk>/', DeleteOrderView.as_view(), name='delete_order'),
    ]

router = routers.DefaultRouter()
router.register(r'product', views.ProductViewSet)
router.register(r'order', views.OrderViewSet)
router.register(r'type_product', views.TypeProductViewSet)

restaurant/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework_simplejwt import views as jwt_views
from persons.urls import router as router_persons
from products.urls import router as router_products
from tables.urls import router as router_tables
from invoice.urls import router as router_invoices

urlpatterns = [
    path('api/order_products/', include(router_products.urls)),
    path('api/persons/', include(router_persons.urls)),
    path('api/tables/', include(router_tables.urls)),
    path('api/invoices/', include(router_invoices.urls)),
    path('', include('persons.urls')),
    path('invoices/', include('invoice.urls')),
    path('tables/', include('tables.urls')),
    path('products/', include('products.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('admin/', admin.site.urls),
    path('api/token/', jwt_views.TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', jwt_views.TokenRefreshView.as_view(), name='token_refresh'),
]

tables/urls.py
from django.urls import path
from rest_framework import routers

from . import views
from .views import ListTableView, RegisterTableView, UpdateTableView, DeleteTableView

app_name = 'table'

urlpatterns = [
    path('table_list', ListTableView.as_view(), name='table_list'),
    path('add_table', RegisterTableView.as_view(), name='add_Table'),
    path('update_table/<int:pk>/', UpdateTableView.as_view(), name='update_table'),
    path('delete_table/<int:pk>/', (DeleteTableView.as_view()), name='delete_table'),
    ]

router = routers.DefaultRouter()
router.register(r'tables', views.TableViewSet)

products/models.py
from django.db import models

from invoice.models import Invoice


class TypeProduct(models.Model):
    name = models.CharField(max_length=150)

    def __str__(self):
        return f'{self.name}'


class Product(models.Model):
    name = models.CharField(max_length=50)
    importe = models.IntegerField()
    type = models.ForeignKey(TypeProduct, on_delete=models.CASCADE)
    price = models.FloatField()

    def __str__(self):
        return f'{self.name}, {self.type}'


class Order(models.Model):
    date = models.DateTimeField(auto_now_add=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    invoice = models.ForeignKey(Invoice, on_delete=models.CASCADE)
    quantity = models.IntegerField()

    def __str__(self):
        return f'{self.product.name}, {self.quantity}'

products/forms.py
from django import forms
from django.forms import TextInput

from products.models import Product, TypeProduct, Order


class TypeProductForm(forms.ModelForm):
    class Meta:
        model = TypeProduct
        fields = '__all__'

        widgets = {
            'reference': TextInput(attrs={
                'class': "form-control mb-3",
                'style': 'max-width: 500px;',
            }),
        }


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

        widgets = {
            'reference': TextInput(attrs={
                'class': "form-control mb-3",
                'style': 'max-width: 500px;',
            }),
        }


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = '__all__'

        widgets = {
            'reference': TextInput(attrs={
                'class': "form-control mb-3",
                'style': 'max-width: 500px;',
            }),
        }

products/views.py
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from rest_framework import viewsets, permissions

from products.forms import OrderForm, ProductForm, TypeProductForm
from products.models import Order, Product, TypeProduct
from products.serializer import ProductSerializer, OrderSerializer, TypeProductSerializer


class TypeProductViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows users to be viewed or edited.
    """
    queryset = TypeProduct.objects.all()
    serializer_class = TypeProductSerializer
    permission_classes = [permissions.IsAdminUser]


class ProductViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows users to be viewed or edited.
    """
    queryset = Product.objects.all()
    serializer_class = ProductSerializer
    permission_classes = [permissions.IsAdminUser]


class OrderViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows users to be viewed or edited.
    """
    queryset = Order.objects.all()
    serializer_class = OrderSerializer
    permission_classes = [permissions.IsAuthenticated]


class ListTypeProductView(ListView):
    model = TypeProduct
    queryset = TypeProduct.objects.all()
    template_name = 'typeProduct/typeProduct_list.html'
    context_object_name = 'typeProduct_list'


class RegisterTypeProductView(CreateView):
    form_class = TypeProductForm
    model = TypeProduct
    template_name = 'typeProduct/add_typeProduct.html'
    success_url = reverse_lazy('products:typeProduct_list')


class UpdateTypeProductView(UpdateView):
    model = TypeProduct
    form_class = TypeProductForm
    pk_url_kwarg = 'pk'
    template_name = 'typeProduct/add_typeProduct.html'
    success_url = reverse_lazy('products:typeProduct_list')


class DeleteTypeProductView(DeleteView):
    model = TypeProduct
    pk_url_kwarg = 'pk'
    template_name = 'typeProduct/delete_typeProduct.html'
    success_url = reverse_lazy('products:typeProduct_list')


class ListProductView(ListView):
    model = Product
    queryset = Product.objects.all()
    template_name = 'product/product_list.html'
    context_object_name = 'product_list'


class RegisterProductView(CreateView):
    form_class = ProductForm
    model = Product
    template_name = 'product/add_product.html'
    success_url = reverse_lazy('products:product_list')


class UpdateProductView(UpdateView):
    model = Product
    form_class = ProductForm
    pk_url_kwarg = 'pk'
    template_name = 'product/add_product.html'
    success_url = reverse_lazy('products:product_list')


class DeleteProductView(DeleteView):
    model = Product
    pk_url_kwarg = 'pk'
    template_name = 'product/delete_product.html'
    success_url = reverse_lazy('products:product_list')


class ListOrderView(ListView):
    model = Order
    queryset = Order.objects.all()
    template_name = 'order/order_list.html'
    context_object_name = 'order_list'


class RegisterOrderView(CreateView):
    form_class = OrderForm
    model = Order
    template_name = 'order/add_order.html'
    success_url = reverse_lazy('products:order_list')


class UpdateOrderView(UpdateView):
    model = Order
    form_class = OrderForm
    pk_url_kwarg = 'pk'
    template_name = 'order/add_order.html'
    success_url = reverse_lazy('products:order_list')


class DeleteOrderView(DeleteView):
    model = Order
    pk_url_kwarg = 'pk'
    template_name = 'order/delete_order.html'
    success_url = reverse_lazy('products:order_list')

templates/product/add_product.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block tittle%} Add a Product {%endblock%}

{% block content %}
<br>
<br>
<br>
<div class="container">
    <div class="row">
        <div class="col-12 col-md-6 offset-md-3">
            <div class="card" id="content-register">
                <div class="card-body">
                    <h3 class="text-center " style="color:dimgrey "> Add a Product</h3>
                    <hr>
                    <form method="POST">

                            {% csrf_token %}
                            {{ form | crispy }}
                             <input type="submit" name="submit" class="btn btn-success btn-md" value="Add">
                            <a class="btn btn-dark" href="{% url 'products:product_list' %}"> Cancel </a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

templates/product/delete_product.html
{% extends 'base.html' %}

{% block Title %} Delete Product{% endblock %}

{% block content %}
    <div class="d-flex justify-content-center">
        <form method="post" novalidate>
            {% csrf_token %}
            <h3 class="mt-5"> ¿Esta seguro de que desea borrar este Product?</h3>
            <div class="text-center mt-4">
                <input value="Confirm" type="submit" class="btn btn-success text-center"/>
                <a class="btn btn-dark" href="{% url 'products:product_list' %}"> Cancel </a>
            </div>
        </form>
    </div>
{% endblock %}

templates/product/product_list.html
{% extends 'base.html' %}

{% block tittle%} List of Products {%endblock%}

{% block content %}
<br>
<br>
<br>
<div class="container">
    <h3 class="text-center " style="color:#181818 ">List of Products </h3>
    <table class="table" id="tabla" style="border: 1px solid darkgrey;
                        border-radius: 20px; background-color:#20c997; opacity:0.9; color:#181818">
        <thead>
            <tr>
                <th scope="col">ID</th>
                <th scope="col">Name</th>
                <th scope="col">Stock</th>
                <th scope="col">Type</th>
                <th scope="col">Price</th>
            </tr>
        </thead>
        <tbody>
            {% for product in product_list %}
            <tr>

                <th scope="row">{{product.id}}</th>
                <td>{{product.name}}</td>
                 <td>{{product.importe}}</td>
                 <td>{{product.type}}</td>
                 <td>{{product.price}}</td>
                <td>
                    <a class="btn btn-primary" style="margin-right: 5px ;" href="{% url 'products:update_product' product.pk %}">Edit</a>
                    <a class="btn btn-danger" href="{% url 'products:delete_product' product.pk %}">Delete</a>
                </td>
        
            </tr>
            {% endfor %}
        </tbody>
        </table>
        <a class="btn btn-primary" style="margin-right: 5px ;" href="{% url 'products:add_typeProduct'%}">Add Type of product</a>
        <a class="btn btn-primary" style="margin-right: 5px ;" href="{% url 'products:typeProduct_list' %}">List All Types of Products</a>
</div>

{% endblock content %}