products/urls.py
from django.urls import path
from rest_framework import routers

from . import views
from .views import ListTypeProductView, RegisterTypeProductView, UpdateTypeProductView, \
    DeleteTypeProductView, ListProductView, UpdateProductView, DeleteProductView, RegisterProductView, ListOrderView, \
    UpdateOrderView, RegisterOrderView, DeleteOrderView

app_name = 'products'

urlpatterns = [
    path('typeProduct_list', ListTypeProductView.as_view(), name='typeProduct_list'),
    path('add_typeProduct', RegisterTypeProductView.as_view(), name='add_typeProduct'),
    path('update_typeProduct/<int:pk>/', UpdateTypeProductView.as_view(), name='update_typeProduct'),
    path('delete_typeProduct/<int:pk>/', DeleteTypeProductView.as_view(), name='delete_typeProduct'),

    path('product_list', ListProductView.as_view(), name='product_list'),
    path('add_product', RegisterProductView.as_view(), name='add_product'),
    path('update_product/<int:pk>/', UpdateProductView.as_view(), name='update_product'),
    path('delete_product/<int:pk>/', DeleteProductView.as_view(), name='delete_product'),

    path('order_list', ListOrderView.as_view(), name='order_list'),
    path('add_order', RegisterOrderView.as_view(), name='add_order'),
    path('update_order/<int:pk>/', UpdateOrderView.as_view(), name='update_order'),
    path('delete_order/<int:pk>/', DeleteOrderView.as_view(), name='delete_order'),
    ]

router = routers.DefaultRouter()
router.register(r'product', views.ProductViewSet)
router.register(r'order', views.OrderViewSet)
router.register(r'type_product', views.TypeProductViewSet)

restaurant/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework_simplejwt import views as jwt_views
from persons.urls import router as router_persons
from products.urls import router as router_products
from tables.urls import router as router_tables
from invoice.urls import router as router_invoices

urlpatterns = [
    path('api/order_products/', include(router_products.urls)),
    path('api/persons/', include(router_persons.urls)),
    path('api/tables/', include(router_tables.urls)),
    path('api/invoices/', include(router_invoices.urls)),
    path('', include('persons.urls')),
    path('invoices/', include('invoice.urls')),
    path('tables/', include('tables.urls')),
    path('products/', include('products.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('admin/', admin.site.urls),
    path('api/token/', jwt_views.TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', jwt_views.TokenRefreshView.as_view(), name='token_refresh'),
]

tables/urls.py
from django.urls import path
from rest_framework import routers

from . import views
from .views import ListTableView, RegisterTableView, UpdateTableView, DeleteTableView

app_name = 'table'

urlpatterns = [
    path('table_list', ListTableView.as_view(), name='table_list'),
    path('add_table', RegisterTableView.as_view(), name='add_Table'),
    path('update_table/<int:pk>/', UpdateTableView.as_view(), name='update_table'),
    path('delete_table/<int:pk>/', (DeleteTableView.as_view()), name='delete_table'),
    ]

router = routers.DefaultRouter()
router.register(r'tables', views.TableViewSet)

templates/typeProduct/add_typeProduct.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block tittle%} Add Type of Products {%endblock%}

{% block content %}
<br>
<br>
<br>
<div class="container">
    <div class="row">
        <div class="col-12 col-md-6 offset-md-3">
            <div class="card" id="content-register">
                <div class="card-body">
                    <h3 class="text-center " style="color:dimgrey "> Add a Type of Products</h3>
                    <hr>
                    <form method="POST">

                            {% csrf_token %}
                            {{ form | crispy }}
                             <input type="submit" name="submit" class="btn btn-success btn-md" value="Add">
                            <a class="btn btn-dark" href="{% url 'products:typeProduct_list' %}"> Cancel </a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

templates/typeProduct/delete_typeProduct.html
{% extends 'base.html' %}

{% block Title %} Delete Type of Product{% endblock %}

{% block content %}
    <div class="d-flex justify-content-center">
        <form method="post" novalidate>
            {% csrf_token %}
            <h3 class="mt-5"> ¿Esta seguro de que desea borrar esta Type of Product?</h3>
            <div class="text-center mt-4">
                <input value="Confirm" type="submit" class="btn btn-success text-center"/>
                <a class="btn btn-dark" href="{% url 'products:typeProduct_list' %}"> Cancel </a>
            </div>
        </form>
    </div>
{% endblock %}

templates/typeProduct/typeProduct_list.html
{% extends 'base.html' %}

{% block tittle%} List of Type of Products {%endblock%}

{% block content %}
<br>
<br>
<br>
<div class="container">
    <h3 class="text-center " style="color:#181818 ">List of Type of Products </h3>
    <table class="table" id="tabla" style="border: 1px solid darkgrey;
                        border-radius: 20px; background-color:#20c997; opacity:0.9; color:#181818">
        <thead>
            <tr>
                <th scope="col">ID</th>
                <th scope="col">Name</th>
            </tr>
        </thead>
        <tbody>
            {% for type in typeProduct_list %}
            <tr>

                <th scope="row">{{type.id}}</th>
                <td>{{type.name}}</td>
                <td>
                    <a class="btn btn-primary" style="margin-right: 5px ;" href="{% url 'products:update_typeProduct' type.pk %}">Edit</a>
                    <a class="btn btn-danger" href="{% url 'products:delete_typeProduct' type.pk %}">Delete</a>
                </td>
        
            </tr>
            {% endfor %}
        </tbody>
        </table>
        <a class="btn btn-dark" href="{% url 'products:product_list' %}"> Go back to products </a>

</div>

{% endblock content %}